### ISSUE TITLE
"It burns" checklist

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#110]
- [ ] write checklist on how to open access to restricted pages in case the login fails

**Comment by tharvik** [comment]
Hum, it's kinda WordPress specific, so not considering the matrix login?
 - if correct as is -> trivial to do, login with admin account and let pages be public
 - if including matrix -> CAS validate **everything**
Both are unsecure which I recommand against.

Isn't, allowing it, working around potential/unwanted errors instead of fixing the source? How much did it happened during the life of the chain?

**Comment by ineiti** [comment]
We had 2 or 3 bit downtimes. The first two were fixed quite fast, while the third lasted 5 days.

Of course fixing the source is the most important part. But chosing between
1. telling all partners "sorry, you cannot watch these secured pages"
and
2. having the "not-so-absolutely secure pages" online to everybody

I chose 2. Then fixing the problem, of course!

**Comment by tharvik** [comment]
>> https://docs.google.com/document/d/1OhtecQpLQXW3R8uwyn_-aemzO_9yl8oGI1lDLSpAPYs/edit#

**Comment by ineiti** [comment]
Did you check with David whether that is understandable to him? I had to search to understand what it actually means - yes, users are dumb :)
